<p align=""><strong><u>REGLAS OFICIALES </u></strong></p>
<ul>
  <li><strong>Nombre de la Concurso de Habilidad: </strong><u>Predictor de Misión Rusia </u><u>Group Stage Phase 1</u><u> </u><u>(</u>&ldquo;Concurso de Habilidad&rdquo;)<strong><u></u></strong></li>
</ul>
<p align=""><strong>NO ES NECESARIA LA COMPRA NI EL PAGO ALGUNO PARA ENTRAR EN O GANAR ESTE CONCURSO DE HABILIDAD.  LA COMPRA NO MEJORARA SUS OPORTUNIDADES DE GANAR. INVALIDO DONDE PROHIBIDO. ABIERTO SOLO PARA CIUDADANOS Y RESIDENTES LEGALES DE LOS ESTADOS UNIDOS MAYORES DE 18 AŇOS. </strong></p>
<p align=""><strong>ESTE CONCURSO DE HABILIDAD DE NINGUNA MANERA ES PATROCINADO, AVALADOS O ADMINISTRADOS POR O ASOCIADO CON APPLE, INC. (&quot;APPLE&quot;)</strong><strong> </strong></p>
<p align=""><strong>2.  Nombre y dirección del Patrocinador: </strong><u>Univision Interactive Media, Inc. </u>con oficinas en <u>8551 N.W. 30th Terrace, Miami, Florida 33122.</u><strong> </strong><br>
  <strong>3.  Nombre y dirección del Co-Patrocinador:</strong> <u>N/A.</u><strong><u> </u></strong><br>
  <strong>4.  Fecha de participación/registro: </strong>El Concurso de Habilidad empieza el 8 de junio de 2018 a las 12:00:01 am hora del Este y finaliza el 29 de junio de 2018 a las 11:59:59pm hora del Este. Todas las participaciones completas deberán ser recibidas antes del 29 de junio de 2018 a las 11:59:59pm hora del Este.<strong><u></u></strong><br>
<strong>5.  Elegibilidad: </strong>Participantes deben ser mayores de 18 años, ciudadanos y residentes legales de los 50 estados de los Estados Unidos de América, con un número de Seguro Social (SS#) o de Impuestos (TIN), quienes no hayan ganado un premio del Patrocinador dentro de los últimos 30 días.  <br>
<strong>6.  Manera de participar: </strong>Para participar debe ser lo siguiente: visitar por Internet a <a href="http://www.univisiondeportes.com/predictor">www.univisiondeportes.com/predictor</a> y siga las instrucciones para suscribirse y participar en el juego Predictor Misión Rusia. Una vez que se suscriben, necesitan:</p>
<ul>
  <li>Seleccionar los equipos que forman parte de cada grupo en la fase de grupos del campeonato mundial de futbol hasta la etapa de postemporada de esa competencia.<strong>&nbsp;</strong></li>
</ul>
<p><strong>7.  Cuantos formatos de participación permitidos:</strong> Participaciones limitadas a uno (1) por persona durante el periodo del Concurso de Habilidad. Solo un premio por hogar.</p>
<p><strong>8.  Manera de elegir al/los Ganador(es): </strong>Un panel de jueces compuesto por empleados del Patrocinador, cuya decisión será final y obligatoria en todos los aspectos, seleccionará al ganador que acumule la mayor cantidad de puntos en el juego Predictor Misión Rusia antes del 29 de junio de 2018. En caso de un empate entre dos o más participantes, el ganador será seleccionado a través de un concurso de escritura.  Cada participante deberá escribir un máximo de 200 palabras explicando porque le gusta jugar el juego de Predictor de Misión Rusia.   El panel de jueces compuesto de empleados seleccionados del Patrocinador seleccionará al ganador de acuerdo con los siguientes criterios: originalidad, creatividad y claridad de expresión. Todos los criterios se ponderarán equitativamente. A continuación, encontrará una descripción detallada del mecanismo del juego: <br>
  <u>Mecanismo del juego:</u></p>
Los participantes seleccionarán el equipo que pasará de primer lugar y al equipo que pasará de segundo lugar de cada grupo a la etapa de la octavos de final de la fase de eliminación. Cada participante obtendrá 3 puntos por cada elección correcta realizada.<br>

<ul type="circle">
  <li>En el caso que haya dos o más      participantes empatados por los premios a primer y segundo puesto, los      participantes ganadores serán seleccionados a través de un concurso de      escritura. Cada participante ganador deberá escribir un máximo de 200      palabras explicando porque le gusta jugar el juego de Predictor de Misión      Rusia.  <a name="_Hlk516146094">Puede      ser en inglés o español.</a></li>
</ul>
<p><strong>9.   Fecha de selección de Ganador(es): </strong>Los Ganadores serán seleccionados en o alrededor del 29 de junio de 2018.<strong><u></u></strong><br>
  <strong>10.  Manera de notificar al/los Ganador(s): </strong>Los Ganadores serán notificados en o alrededor del 29 de junio de 2018 por teléfono o correo electrónico.  En caso que el Patrocinador no pueda localizar a un posible ganador dentro de los veinticuatro (24) horas siguientes a la fecha en que intenten notificar al posible ganador, el Patrocinador seleccionará a un nuevo ganador de acuerdo con estas reglas.  El ganador tiene que firmar un documento de liberación y elegibilidad y un formulario W-9 (si es aplicable) antes de recibir el premio.  Este documento tiene que ser recibidos por el Patrocinador dentro de 2 días después de haber sido mandado.  Adicionalmente, si el posible ganador resulta no ser elegible, se considerará como si el posible ganador hubiere rechazado el premio, y el Patrocinador seleccionarán a un nuevo ganador. <br>
  <strong>11.  Intencionalmente Omitido.</strong><br>
  <strong>12.  Premio(s) y su valor aproximado: </strong>Habrá<strong> </strong>un (1) premio de primer lugar y un (1) premio de segundo lugar otorgado en este Concurso de Habilidad.  El premio de Primer Lugar consiste en un cheque de cajeros de $3,000.  El premio de Segundo Lugar conste en un cheque cajeros de $1,500.<br>
  El valor aproximado del todos los premios es $4,500.<br>
  <strong>Oportunidades de ganar dependerán del número de participantes. </strong>Esta abierto únicamente a ciudadanos y residentes legales de los Estados Unidos de América, con un número de Seguro Social.  <strong>Las personas incluidas en cualquiera de las siguientes categorías no podrán participar ni ganar un premio: (a) personas que a partir de o con posterioridad del Concurso de Habilidad sean o hayan sido empleados o agentes de los Patrocinadores, o sus matrices, filiales, subsidiarias, agencias de servicio o contratistas independientes; (b) personas que estén involucradas en el desarrollo, producción, distribución de materiales, o de la selección de los ganador de este Concurso de Habilidad; y (c) personas que formen parte de la familia inmediata de, o que habiten en la misma casa de alguna de las personas incluidas en cualquiera de las categorías anteriores.  </strong><br>
  Todos los formatos de participación, si los haya, serán propiedad del Patrocinador y no serán devueltos al participante.  El Patrocinador se reserva el derecho de descalificar o rehusar publicar cualquier participación y/o fotografía en su sola discreción. El Patrocinador no será responsable por la pérdida, robo o desvío de las fotografías y/o formatos de participación, ni por fotografías y formatos de participación reproducidos mecánicamente, ilegibles, incompletos, inexactos, dañados o tardíos. El Patrocinador no es responsable por llamadas que se desconecten, equivocadas, o líneas ocupadas, ni por información incorrecta o inexacta. Las fotografías y formatos de participación reproducidos mecánicamente, ilegibles, incompletos o inexactos serán nulos. Cada participante está de acuerdo en permitir que el Patrocinador utilice su nombre, dirección, ciudad, estado, fotografía, voz, cinta de video o cualquier figura semejante con propósitos de publicidad sin compensación adicional alguna. El Patrocinador puede utilizar la información proporcionada por el participante para ofrecerle información de otras ofertas, productos o servicios, según la política de privacidad de Univision, disponible en <a href="http://www.univision.com">www.univision.com</a>.  La información proporcionada por el participante se hará disponible al Patrocinador solamente.</p>
<p>Al participar usted otorga al Patrocinador el derecho mundial exclusivo, plenamente pagado, libre de regalías, pero no la obligación, de usar, copiar, reproducir, publicar, distribuir, exhibir, transmitir y presentar su fotografía, en todo medio de difusión y por cualquier medio, sea actualmente conocido o se desarrolle en el futuro, incluyendo, con carácter no exclusivo, anunciar, exhibir y de otro modo disponer de su fotografía para publicar por Internet, televisión, móvil, radio, y someterla a la vista del público, y usar, reproducir y publicar su nombre, semblante, imagen, fotografía, actuación y otros elementos de su aparición o imagen para llevar a cabo y promover el Concurso de Habilidad y/los Patrocinadores, en cada caso SIN AVISO, COMPENSACION O ATRIBUCION ALGUNA A USTED. </p>
<p>USTED COMPRENDE Y ACEPTA QUE LA ÚNICA CONTRAPRESTACIÓN QUE RECIBIRÁ POR ESTE OTORGAMIENTO DE DERECHOS ES LA PUBLICIDAD QUE PUEDA RECIBIR EN LA PUBLICACIÓN O TRANSMISIÓN DE SU FOTOGRAFÍA Y/O LA ANUNCIACIÓN DE USTED COMO LA PERSONA QUE PARTICIPÓ EN ESTE CONCURSO DE HABILIDAD.</p>
<p>Todas las decisiones del Patrocinador serán finales y obligatorias en todos los sentidos. Cada ganador podrá tener que firmar una liberación de responsabilidad. Si el ganador resulta no ser elegible; si no se puede notificar al ganador como mencionado anteriormente o si el ganador no recoge el premio como detallado anteriormente, se considerará como si el ganador hubiese rechazado el premio y el Patrocinador podrá seleccionar a un ganador nuevo si el tiempo lo permite. Para reclamar premios, ganador serán requeridos proveer identificación aceptable al Patrocinador y recoger premios como sean instruidos. Ganador(es) no puede(n) sustituir el premio por su equivalente en efectivo o por un crédito.  El premio no se puede reemplazar si es perdido o robado. El Patrocinador se reserva el derecho de sustituir a su discreción cualquiera o todos los premios con cualquier artículo o servicio de valor semejante o mayor.  Los premios no pueden ser cedidos o transferidos por el (los) ganador(es).  </p>
<p>El Patrocinador se reserva el derecho de modificar o terminar este Concurso de Habilidad por cualquier razón incluyendo si existe fraude, fallas técnicas o cualquier otro factor más allá del control del Patrocinador que dañe la integridad de la Concurso de Habilidad, determinado por el Patrocinador en su sola discreción.  El Patrocinador podrá descalificar a cualquier persona que, a su sola discreción, considere haya violado estas Reglas Oficiales o cualquier aspecto de la Concurso de Habilidad.  El (los) participante(s) está(n) de acuerdo en:  (a) estar sujetos a las Reglas Oficiales y las decisiones del Patrocinador, y (b) liberar y mantener en paz y a salvo al Patrocinador, el (los) Co-Patrocinador(es) y a sus respectivos matrices, filiales, estaciones, subsidiarias, y contratistas independientes, y sus respectivos directores, funcionarios, empleados, y agentes, inclusive a las agencias de publicidad y Concurso de Habilidad, de cualquier y toda responsabilidad con respecto a la aceptación, posesión o uso (o el mal uso) de los premios y/o de la participación en la Concurso de Habilidad.</p>
<p>Los impuestos (federales, estatales, y locales) son la responsabilidad exclusiva del ganador y es posible que se requiera que cada ganador prepare formularios de impuestos. Si el ganador ha recibido otros premios del Patrocinador durante el año actual, y si el valor total de dichos premios excede $600, el ganador tendrá que proveer su Número de Seguro Social o Número de Identificación de Impuestos para recibir el premio. Estas Reglas Oficiales están sujetas a las leyes del Estado donde se ubica el Patrocinador, haciendo caso omiso de los principios de conflicto de leyes.</p>
<p>Para obtener la lista de ganador(es) la cual estará disponible después de que termine la Concurso de Habilidad, envíe a &ldquo;Predictor de Misión Rusia Group Stage Phase 1 Concurso de Habilidad – Lista de Ganador(es)&rdquo;, a la dirección del Patrocinador antes indicada, un sobre por separado dirigido a usted mismo con estampilla postal pre-pagada.</p>
<p>Para obtener una copia de estas Reglas Oficiales, envíe a &ldquo;Predictor de Misión Rusia Group Stage Phase 1 Concurso de Habilidad – Reglas Oficiales&rdquo; a la dirección del Patrocinador antes indicada, un sobre por separado con estampilla postal pre-pagada y dirigido a usted mismo.</p>
<p>En el caso que hubiese participación en línea: Se prohíbe el uso de software para la entrada automatizada de formatos de participación.  Los formatos de participación hechos en línea con múltiples direcciones de correo electrónico, bajo múltiples identidades o por medio de cualquier artefacto o artificio utilizado para participar múltiples veces se considerarán nulos.  Si el ganador es un participante en línea, se considerará que el formato de participación ganador es el que haya sido enviado por el poseedor autorizado de la cuenta de la dirección de correo electrónico que envió el dicho formato. El poseedor autorizado de la cuenta de correo electrónico será considerado como la persona física a la que le es asignada una dirección del correo electrónico por medio de un proveedor de acceso a internet, por un proveedor de servicio u otra organización que sea responsable de asignar direcciones de correo electrónico o por el dominio asociado con la dirección de correo electrónico enviada.  El Patrocinador no será responsable por la transmisión de información incorrecta o inexacta contenida en los formatos de participación, por los errores técnicos, la pérdida o demora de la transmisión de datos, la omisión, interrupción, supresión, defectos o fallas en la línea de red telefónica, o del equipo de cómputo, software, o por la imposibilidad de acceso a cualquier servicio o sitio en línea, la imposibilidad de enviar el formato de participación, o por cualquier otro error o disfunción, o cualquier daño causado al equipo de cómputo del participante o de cualquier otra persona que resulte de la descarga de materiales o información o de la participación en esta Concurso de Habilidad, o por la pérdida, robo, demora, pérdida en correo, datos ilegibles de los formatos de participación o por ser enviados a un lugar incorrecto.</p>
<p>Si esta Concurso de Habilidad o cualquier sitio de la red asociado con éste (o cualquier porción del mismo) se llegare a corromper o no permitiere la entrada a la Concurso de Habilidad, o si la infección por virus de computadora, bugs, manipulación, intervención no autorizada, acciones de los participantes, por fraude, fallas técnicas, o por cualquier otra causa, que en la opinión del  Patrocinador, corrompa o afecte la administración, seguridad, imparcialidad, integridad, o la operación apropiada de esta Concurso de Habilidad, el Patrocinador se reserva el derecho, a su única discreción, de descalificar a cualquier individuo implicado en tal acción, y/o a cancelar, terminar, modificar o suspender esta Concurso de Habilidad o alguna porción del mismo.  La tentativa, por parte de algún participante o de cualquier otro individuo, de dañar deliberadamente el servicio en línea o el sitio en la red, así como el intento de socavar la operación legítima de esta Concurso de Habilidad, se considerará una violación a las leyes penales y civiles.  El Patrocinador se reserva el derecho de hacer valer su derecho de reclamar el pago de daños y/u otros perjuicios en la extensión más amplia permitida por la ley.</p>
<p align=""><strong><em>ENGLISH VERSION OF THE &ldquo;RULES&rdquo; PROVIDED FOR CONVENIENCE ONLY.</em></strong><br>
  <strong><em>In the event of a conflict between the Spanish and English Rules, the Spanish Rules will govern.</em></strong><strong><em>&nbsp;</em></strong></p>
<p align=""><strong><em>THE ENGLISH VERSION OF THE &ldquo;RULES&rdquo; IS PROVIDED FOR CONVENIENCE ONLY.</em></strong><br>
  <strong><em>IN THE EVENT OF A CONFLICT BETWEEN THE SPANISH AND ENGLISH RULES,</em></strong><br>
  <strong><em>THE SPANISH RULES WILL GOVERN.</em></strong></p>
<p align=""><strong><u>Official Rules</u></strong><strong> </strong></p>
<p><strong>1.        Name of Skill Contest:</strong><strong> </strong><u>Predictor de Misión Rusia </u><u>Group Stage Phase 1</u><u> (&ldquo;Skill Contest&rdquo;)</u></p>
<p align=""><strong>NO PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO WIN.  A PURCHASE WILL NOT IMPROVE THE CHANCES OF WINNING.  YOU HAVE NOT YET WON. VOID WHERE PROHIBITED.   </strong><strong>OPEN ONLY TO CITIZENS AND LEGAL RESIDENTS IN THE UNITED STATES OLDER THAN 18 YEARS OF AGE. </strong></p>
<p align=""><strong>THIS SKILL CONTEST IS IN NO WAY SPONSORED, ENDORSED, OR ADMINISTERED BY OR ASSOCIATED WITH APPLE, INC. (&ldquo;APPLE&rdquo;)</strong></p>
<p><strong>2. Name and address of Sponsor</strong>: <u>Univision Interactive Media, Inc. </u>with offices in<u> </u><u>8551 N.W. 30th Terrace, Miami, Florida 33122</u><u>.</u> <br>
              <br>
  <strong>3. Name and address of Co- Sponsor(s): </strong><u>N/A.</u> <br>
                          <br>
  <strong>4. Date of participation</strong>: The Skill Contest begins on June 8, 2018 at 12:00:01 am Eastern Standard Time (&ldquo;ET&rdquo;), and ends on June 29, 2018 at 11:59:59pm ET. All completed entries must be received before June 29, 2018 at 11:59:59pm ET. </p>
<p><strong>5. Eligibility</strong>: Participants must be over18 years of age, legal residents of the 50 states of the United States, with a Social Security Number (SS#) or Tax Identification Number (TIN), who have not won a prize from the Sponsor within the last 30 days. </p>
<p><strong>6. How to Enter:</strong>  To participate visit <a href="http://www.univisiondeportes.com/predictor">www.univisiondeportes.com/predictor</a> and follow the instructions to subscribe and participate in the Predictor Misión Rusia game.  Once they subscribe, they need to do the following:</p>
<ul type="disc">
  <li>Select      the teams that make it from each group in the world soccer championship group      stage to the playoff stage of that competition</li>
</ul>
<p><strong>7. Number of entries allowed per person: </strong>Entries limited to one (1) per person during the Skill Contest period.<br>
  <strong></strong><br>
<strong>8. Method of Selecting Winner(s):</strong> A panel of judges comprised of selected employees of Sponsor, whose decision will be final and binding in all respects, will select the winners according to the following criteria: originality, creativity, and clarity of expression.  All criteria shall be weighed equally.  In case of a tie between two or more participants, the winner will be selected through a writing contest. Each participant must write a maximum of 200 words explaining why he/she likes to play the Mission Predictor game Russia. The panel of judges composed of selected employees of the Sponsor will select the winner according to the following criteria: originality, creativity and clarity of expression. All the criteria will be weighted equally. Below you will find a detailed description of the game mechanism:</p>
<ul>
  <li><a name="_Hlk516236894">Participants will select the first place team and second place team from each group that move on to the Round 16 stage to the knockout stage. Each participant will earn 3 points for every correct choice made</a></li>
</ul>
<ul>
  <li>In the case 2 or more participants are tied for first and second prizes, the winning participants will be selected through a writing contest. Each participant will write an excerpt of a maximum of 200 words explaining why he likes to play the Predictor de Misión Rusia. Excerpt can be in English or Spanish  <strong>&nbsp;</strong></li>
</ul>
<p><strong>9. Date Winner will be selected: </strong>The Winner will be selected on or around June 29, 2018.</p>
<p><strong>10. Method of notifying Winner(s)</strong>: Sponsor will contact the potential Winners on or about June 29, 2018 via telephone or email.&nbsp; In the event that Sponsor cannot reach the potential winner within twenty-four (24) hours or if the potential winner is ineligible, it will be deemed as if the winner has rejected the prize and Sponsor will select a new potential winner according to these Official Rules. Prior to being named the official winner, the potential winner will be required to sign and return a declaration of eligibility, a W-9 (if applicable), a liability release and, except where prohibited, a publicity release. Failure to return such documents signed within two (2) days of receiving notification, or if prize or prize notification is returned unsigned or as undeliverable, such potential winner will be deemed disqualified and the Prize will be forfeited and Sponsors may award the prize to an alternate winner, at Sponsors&rsquo; sole discretion.<br>
  <br>
  <strong>11. Intentionally Omitted.</strong></p>
<p><strong>12. Prize(s) and estimated value</strong>: There will be one (1) First Place prize and one (1) Second Place prize awarded in this Skill Contest.   The First Place prize consists of a cashier&rsquo;s check in the amount of $3,000.  The Second Place prize consists of a cashier&rsquo;s check in the amount of $1,500.</p>
<p>The approximate retail value of all prizes is $4,500.</p>
<p>Odds of winning depend on the number of participants.  Is open only to citizens and legal residents of the United States of America, with a Social Security number.  Persons in any of the following categories are not eligible to participate or win a prize: (a) persons who from and after the Skill Contest were or are employees or agents of Sponsor or its parent, affiliates, subsidiaries, agencies service or independent contractors; (b) persons who are engaged in the development, production, distribution of materials, or the selection of the winners of this Skill Contest; and (c) persons that they are part of the immediate family of or who reside in the same household of any of the persons included in any of the preceding categories.  </p>
<p>All entries will become the property of Sponsor and will not be returned to the participant. Sponsor reserves the right to disqualify or refuse to publish any participation and/or photography at its sole discretion. Sponsor will not be responsible for loss, theft or diversion of the photographs and/or entries, or for photographs and formats of participation, mechanically reproduced, illegible, incomplete, inaccurate, damaged or delayed. Sponsor is not responsible for calls that are disconnected, wrong, or busy lines, or for incorrect or inaccurate information. Photographs and formats of participation, mechanically reproduced, illegible, incomplete or inaccurate entries are void. Each participant agrees to allow Sponsor to use his/her name, address, city, State, photograph, voice, video tape, or any similar figure for the purposes of advertising without further compensation. The Sponsor can use the information provided by the participant to provide you with information and other offers, products or services, according to the privacy policy of Univision, available on <a href="http://www.univision.com">www.univision.com</a>.  The information provided by the participant will be available to the Sponsor only.</p>
<p>By participating you grant to Sponsor the world exclusive, fully paid, free of royalties, but not the obligation to, use, copy, reproduce, publish, distribute, display, transmit and present your photograph, in any means of diffusion and by any means, is currently known or develops in the future, including, on a non-exclusive basis, announce, display, and otherwise dispose of your photograph to publish on the Internet Mobile, TV, radio, and submit it to the public eye, and use, reproduce and publish his name, face, image, photograph, acting and other elements of his appearance or image to carry out and promote the Skill Contest and / Sponsors, in each case without notice, compensation or attribution whatsoever to you.</p>
<p>YOU UNDERSTAND AND ACCEPT THAT THE ONLY CONSIDERATION THAT YOU WILL RECEIVE FOR THIS GRANT OF RIGHTS IS ADVERTISING THAT YOU WILL RECEIVE BY THE PUBLICATION OR TRANSMISSION OF YOUR PHOTOGRAPH OR ANNOUNCING YOU AS THE PERSON THAT PARTICIPATED IN THIS COMPETITION.</p>
<p>All decisions of Sponsor are final and binding in all respects. Each winner and each guest of the winner, if applicable, will have to sign a release of liability. If the winner is not eligible; If the winner cannot be notified as mentioned previously, or if the winner does not collect the prize as detailed above, it shall be deemed as if the winner has rejected the prize and Sponsor will select a new winner if time permits. To claim prizes, winners will be required to provide identification acceptable to the Sponsor and collect prizes as they are instructed. Winner (s) may not (n) substitute the prize for its cash equivalent or for a credit. The prize cannot be replaced if it is lost or stolen. Sponsor reserves the right to replace at its discretion any and all prizes with any item or service of similar value or higher. The prizes may not be assigned or transferred by the (s) winner (s).</p>
<p>Sponsor reserves the right to modify or terminate this Skill Contest for any reason including if fraud, technical failures or any other factor beyond the control of Sponsor that damages the integrity of the Skill Contest, determined by Sponsor in its sole discretion. Sponsor may disqualify any person who, in its sole discretion, deems to have violated these official rules or any aspect of the Skill Contest. The (s) participant (s) is (n) agreed to: (a) be subject to the official rules and the decisions of the Sponsor, and (b) release, and maintain peace and safe to the Sponsor, the (the) co-Sponsor (s) and their respective parent, affiliates, stations, subsidiaries, and independent contractors, and their respective directors, officers, employees, and agents, including advertising and Skill Contest agencies , from any and all liability with respect to acceptance, possession or use (or misuse) of prizes or participation in the Skill Contest.</p>
<p>Taxes (Federal, State, and local) are the sole responsibility of the winner and it may be required that each winner prepare tax forms. If the winner has received other awards of the Sponsor during the current year, and the total value of these prizes exceeding $600, the winner will have to provide your Social Security number or tax ID number to receive the award. These official rules are subject to the laws of the State where the Sponsor, ignoring the principles of conflict of laws is located.<br>
  For the list of winner(s) which will be available after the end of the Skill Contest, send to &ldquo;Predictor de Misión Rusia Group Stage Phase 1 - list of winner (s)&quot;, to the address of the Sponsor listed above, with a self-addressed stamped envelope with prepaid postal stamp.</p>
<p>To obtain a copy of these official rules, send &quot; Predictor de Misión Rusia Group Stage Phase 1 – rules official&quot; to the address of the Sponsor listed above, with a self-addressed stamped envelope with prepaid postal stamp.</p>
<p>In the event of an online participation: the use of software for the automated entry of participation is prohibited. The formats of participation made in line with multiple e-mail addresses, under multiple identities or by means of any other device or artifice to enter multiple times will be deemed invalid. If the winner is a participant in line, is considered to be the winning format of participation which has been sent by the authorized holder of the account of the e-mail address that sent the said format. The possessor authorized e-mail account will be considered as the natural person who is assigned a direction of electronic mail by a provider of internet access, a service provider or other organization that is responsible for assigning email addresses or the domain associated with the submitted e-mail address. Sponsor is not responsible for the transmission of incorrect or inaccurate information contained in the formats of participation, by technical errors, loss or delay in the transmission of data, omission, interruption, deletion, defects or faults on the line telephone network, or the computer equipment, software, or the impossibility of access to any service or site online the inability to send the format of participation, or any other error or malfunction, or any damage to the computer equipment of the participant or any other person that results from the download of materials or information, or from participation in this Skill Contest, or for the loss, theft, delay, loss in mail, unreadable data formats of participation or be sent to a wrong place.</p>
<p>If this Skill Contest or any Web site associated with this (or any portion thereof) changes to corrupt or they are not permitted entry to the Skill Contest, or if infection by virus, computer bug, manipulation, unauthorized intervention, actions participants, by fraud, troubleshooting techniques, or any other cause, which in the opinion of the Sponsor corrupt or impair the Administration, security, fairness, integrity, or proper operation of this Skill Contest, Sponsor reserves the right, in its sole discretion, to disqualify any individual implicated in such action, and/or to cancel, terminate, modify or suspend this Skill Contest or any portion thereof. The attempt by a participant or any other individual, deliberately damage online service or the Web site, as well as the attempt to undermine the legitimate operation of this Skill Contest, will be considered a violation of criminal and civil laws. The Sponsor reserves the right to assert his right to claim the payment of damages and/or other damages the wider extent permitted by law.</p>
